# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Event.create!(name: "Fête nationale", start: "2017-05-24 13:00", venue: "Résidence de France", subject: "Invitation 14 Juillet")

Category.create!(event: Event.first, name: "SCAC")
Category.create!(event: Event.first, name: "SCG")
Category.create!(event: Event.first, name: "SSI")
Category.create!(event: Event.first, name: "SEMA")
Category.create!(event: Event.first, name: "DUA")
Category.create!(event: Event.first, name: "CHAN")
Category.create!(event: Event.first, name: "PRESSE")


Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Yoann', last_name: 'Lecuyer')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Claude', last_name: 'Lecuyer')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Edueard', last_name: 'Acero')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luis Fernando', last_name: 'Afanador')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Lina Maritza', last_name: 'Amador')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Solorzano', last_name: 'Andreina')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Botero', last_name: 'Andres')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Soto', last_name: 'Angie')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jorge', last_name: 'Arabia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fernando', last_name: 'Araujo-Velez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Manuel', last_name: 'Arevalo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ana', last_name: 'Arizabaleta')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Dario', last_name: 'Arizmendi')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Reinhard', last_name: 'Babel')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Pedro', last_name: 'Badran')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jaime', last_name: 'Baena')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Stephanie', last_name: 'Barraud')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Paul', last_name: 'Barthe')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ana Maria', last_name: 'Bautista')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Felipe', last_name: 'Bedoya')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Patrick', last_name: 'Bele')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mickael', last_name: 'Benetti')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Christophe', last_name: 'Bergeon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jean - Claude', last_name: 'Bessudo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Samy', last_name: 'Bessudo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Andres', last_name: 'Betancourt')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Benjamin', last_name: 'Bobbe')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Israel', last_name: 'Bolanos')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Marta', last_name: 'Botija')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Christophe', last_name: 'Bouton')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Rachel', last_name: 'Brazier')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Hernan', last_name: 'Briceno')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Victor', last_name: 'Brun')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mario', last_name: 'Buendia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Carlos', last_name: 'Cabanillas')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Pierre-Yves', last_name: 'Calloc\'h')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Claudia', last_name: 'Camargo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Federico', last_name: 'Camerlinckx')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fidel', last_name: 'Cano Correa')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Marta', last_name: 'Canorea')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Elisa', last_name: 'Carbonell')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Eduardo', last_name: 'Carreno')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Neil', last_name: 'Carvajal')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Pablo', last_name: 'Castillo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Guillermo', last_name: 'Castro')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Hugo', last_name: 'Chaparro')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Laurent', last_name: 'Charpin')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Claude', last_name: 'Chassaing')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Christophe', last_name: 'Chavagneux')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Camilo', last_name: 'Chaves')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Roldan Gonzalez', last_name: 'Clara Luz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Roux', last_name: 'Clement')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'David', last_name: 'Collas')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Esteban', last_name: 'Constain')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jorge', last_name: 'Contreras')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Maria Leonor', last_name: 'Cordoba')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan David', last_name: 'Correa')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Philipp', last_name: 'Crettex')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Viktoria', last_name: 'Csonka')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Antonio', last_name: 'Cuoco')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Antonio', last_name: 'De Cea')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Sylvie', last_name: 'Delesmontey')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Guillermo', last_name: 'Delgado')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Patrick', last_name: 'Delmas')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Philippe', last_name: 'Demaria')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Marie-Eve', last_name: 'Detoeuf')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Zarate', last_name: 'Diana')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luis', last_name: 'Diaz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Joel', last_name: 'Doglioni')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Helio', last_name: 'Duenha')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Lisandro', last_name: 'Duque')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Patrick', last_name: 'Egloff')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Katherine', last_name: 'Eissner')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Manuel', last_name: 'Escobar')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gustavo', last_name: 'Espinosa')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Edson Yersey', last_name: 'Esquivel')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Hector Abad', last_name: 'Faciolince')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Diego', last_name: 'Fandino')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Augusto', last_name: 'Felix')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Daniel', last_name: 'Fernandez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luis', last_name: 'Fernandez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Marta', last_name: 'Ferraro')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jan', last_name: 'Fischer')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jelle', last_name: 'Floot')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gabriel', last_name: 'Florez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Catalina', last_name: 'Forero')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gloria', last_name: 'Franco')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Valiere', last_name: 'Francoise')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jose M.', last_name: 'Fuentes')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Andres Mitsu', last_name: 'Fuse Pimienta')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Dino', last_name: 'Gallo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jennifer', last_name: 'Garces')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luz Marina', last_name: 'Garcia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Peithi', last_name: 'Garcia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gabriel', last_name: 'Garcia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Francisco', last_name: 'Garcia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Antonio', last_name: 'Garcia Roger')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Diego', last_name: 'Gaska')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Hubert', last_name: 'Gehring')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Bjorn', last_name: 'Gehrmann')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Sarah', last_name: 'Gehrmann')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mario', last_name: 'Genz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Santiago', last_name: 'Giraldo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luz Elena', last_name: 'Godoy')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Yolanda', last_name: 'Gomez Torres')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Javier', last_name: 'Gonzalez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Joshua', last_name: 'Goodman Y Sra.')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jean-Philippe', last_name: 'Goudet')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jana', last_name: 'Gruntoradova')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Carlos', last_name: 'Guerrero')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Claudia', last_name: 'Gurisatti')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jonathan', last_name: 'Guyot')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Barbara', last_name: 'Haeming')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mathias', last_name: 'Held')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Olivier', last_name: 'Huot')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ignacio', last_name: 'Iglesias')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Martin', last_name: 'Jaggi')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ferdinand', last_name: 'Jenrich')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Munoz', last_name: 'Juan Manuel')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Isabelle', last_name: 'Kawka')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Yves', last_name: 'Kerouas')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Katja', last_name: 'Kessing')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Rene', last_name: 'Klemm')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Johann', last_name: 'Koller')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Eliska', last_name: 'Krausova')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Torsten', last_name: 'Krempin')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Sergio', last_name: 'Krsnik')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Johannes', last_name: 'Kulms')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luis', last_name: 'Lara')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Cecile', last_name: 'Lavergne')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Breda', last_name: 'Lee')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Catherine', last_name: 'Leost')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Thomas', last_name: 'Liebault')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Margot', last_name: 'Loizillon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ximena', last_name: 'Lopez Arias')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Maria Claudia', last_name: 'Lopez Sorzano')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Manuel', last_name: 'Lucena')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Maxime', last_name: 'Luger')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Philipp', last_name: 'Lustenberger')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Paola', last_name: 'Lynett')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jessica', last_name: 'Malamba')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Adrien', last_name: 'Martinez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Liodegar', last_name: 'Martinez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jonathan', last_name: 'Masmela')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Laurent Aissa', last_name: 'Mchrigui')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mario', last_name: 'Mendoza')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Claire', last_name: 'Meric')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Diego', last_name: 'Millan')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fredy', last_name: 'Mogollon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Edgar', last_name: 'Mohs')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Esteban', last_name: 'Montano Vasquez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Miriam', last_name: 'Montes')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Edgar', last_name: 'Moreno')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Thierry', last_name: 'Moulins')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Julieta', last_name: 'Mrocek')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gregory', last_name: 'Munoz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Hassam', last_name: 'Nassar')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mariana', last_name: 'Ocampo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mario', last_name: 'Ospina')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'William', last_name: 'Ospina')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ricardo', last_name: 'Ospina')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Anna', last_name: 'Oviedova')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Efrain', last_name: 'Pachon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Susana', last_name: 'Palacios')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Florence', last_name: 'Panoussian')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fiorella', last_name: 'Papa')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Laura Carolina', last_name: 'Pava')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Vanessa', last_name: 'Peidro')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luis', last_name: 'Pertusa')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Olivier', last_name: 'Pradet')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fernando', last_name: 'Quiroz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Maria Angelica', last_name: 'Ramos')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jorge Franco', last_name: 'Ramos')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gunter', last_name: 'Rauer')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Guillaume', last_name: 'Regis')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Cecile', last_name: 'Renaudo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Maria Eugenia', last_name: 'Rey')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Edouard', last_name: 'Robart')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Alejandro', last_name: 'Rodriguez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Natalia', last_name: 'Rojas')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan David', last_name: 'Rojas Berincua')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Patricia', last_name: 'Romero')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Nicolas', last_name: 'Rozo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Agustin', last_name: 'Rubio')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Yolanda', last_name: 'Ruiz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'David', last_name: 'Saavedra')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gines', last_name: 'Sabater')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Anabel', last_name: 'Saez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Francisco', last_name: 'Sandoval')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Christoph', last_name: 'Saurenbach')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Sven', last_name: 'Schewe')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Felix', last_name: 'Schmitt')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Eliana', last_name: 'Schneider')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jens-Uwe', last_name: 'Schuetz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Cedric', last_name: 'Schupisser')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Bernardo', last_name: 'Serafim')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Enrique', last_name: 'Serrano')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Christian', last_name: 'Sieber')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ricardo', last_name: 'Silva')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Richard', last_name: 'Skacel')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Pavla', last_name: 'Skacelova')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Milos', last_name: 'Sklenka')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Lieven', last_name: 'Slachmuylders')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luis Armando', last_name: 'Soto')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Sophie', last_name: 'Stallini')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Christian', last_name: 'Steiner')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jascha', last_name: 'Stiller')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Alin', last_name: 'Tapalaga')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Marina', last_name: 'Tejedor')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Pascal', last_name: 'Tissot')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jose A.', last_name: 'Togores')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Julian', last_name: 'Torres')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Gabriel', last_name: 'Uribe')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jorge', last_name: 'Valderrama')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mauricio', last_name: 'Vargas')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Carlos', last_name: 'Vives')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Thomas', last_name: 'Voigt')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Heinz', last_name: 'Von Appen')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Marcus', last_name: 'Von Essen')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Lothar', last_name: 'Witte')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ana Paula', last_name: 'Zacarias')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Carmenza', last_name: 'Zarate')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Daniel', last_name: 'Zimmermann')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Hernan', last_name: 'Zuleta')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Alberto', last_name: 'Zuniga')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jeroen', last_name: 'Cooreman')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Johan', last_name: 'D\'Halleweyn')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luc', last_name: 'Pirson')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Marjorie', last_name: 'Inghels')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luc', last_name: 'Gerard')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Adivignon', last_name: 'Depaepe')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'David', last_name: 'Dewez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Francisco', last_name: 'Fandino Fineau')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Marleen', last_name: 'Palmaers')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Filip', last_name: 'Otten')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Daniel', last_name: 'Soto Zeevaert')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Erwin', last_name: 'De Nys')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jan', last_name: 'Dewaegemaeker')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Simon', last_name: 'De Man')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Maximilien', last_name: 'De Coster')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Tom', last_name: 'Allegaert')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jean-Pierre', last_name: 'De Meerleer Sanchez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jean-Pierre', last_name: 'Lenaerts')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Xavier', last_name: 'Ryngaert')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Daniel', last_name: 'Del Rio')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Guido', last_name: 'Lefèvre')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ergin ', last_name: 'Dinc ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gökay ', last_name: 'Dagdelen ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Önder ', last_name: 'Boyaci')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Esra ', last_name: 'Özbek ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Soner ', last_name: 'Akdokur ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Yesim ', last_name: 'Charum ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ömer ', last_name: 'Karatekin ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ugur ', last_name: 'Eser')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Sebastian ', last_name: 'Galvis ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Narda ', last_name: 'Zuluaga')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Hernan', last_name: 'Vieira')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jean ', last_name: 'Courtade')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ana ', last_name: 'Mazuera')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Carolina ', last_name: 'Plata')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Julian', last_name: 'Jimenez Riviere')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fernando ', last_name: 'Lecaros')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Luis Alfredo ', last_name: 'Perez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Oswaldo ', last_name: 'Perez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Paula ', last_name: 'Ruiz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Maria Alejandra', last_name: ' Navas')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Yves', last_name: ' Millière')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ignacio ', last_name: 'Perez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Pablo', last_name: 'Roa')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Myriam ', last_name: 'Forero')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Myriam ', last_name: 'De Campos')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Paul ', last_name: 'Pico')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Pavel', last_name: 'Sergiev')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Julio', last_name: 'Calderon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Eduard', last_name: 'Soto Guerrero')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Tatiana', last_name: 'Bensa')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Nilton', last_name: 'Bernal')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Bonner', last_name: 'Mosquera')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Astolfo', last_name: 'Romero')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Guillermo', last_name: 'Goelkel')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Willington', last_name: 'Ortiz')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Dino', last_name: 'Gallo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Gerardo', last_name: 'Bedoya')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Carlos', last_name: 'Valencia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Leider', last_name: 'Preciado')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Hernando', last_name: 'Tovar')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'William', last_name: 'Morales')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Adolfo', last_name: 'Valencia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Enrique', last_name: 'Camacho')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Efrain', last_name: 'Pachon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Acisclo', last_name: 'Cordoba')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Agustin', last_name: 'Julio')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Alexis', last_name: 'Garcia')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Alfonso', last_name: ' Canon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ana', last_name: 'Mazuera')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Annie', last_name: 'Nino')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Cerveleon', last_name: 'Cuesta')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Diana Carolina', last_name: ' Rincon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Eduardo', last_name: 'Canon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fernando', last_name: 'Lecaros')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fredy', last_name: 'Leon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'German', last_name: 'Morales')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ignacio', last_name: 'Perez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jean', last_name: 'Courtade')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan Pablo', last_name: 'Roa')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Karen Maria ', last_name: 'Pena')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Melanie ', last_name: 'Nino')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Moises', last_name: 'Pachon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Myriam', last_name: 'De Campos')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Roberto Alfonso', last_name: 'Canon')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Victor', last_name: 'Rosas')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Oscar', last_name: 'Cortes')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Fabian', last_name: 'Lopez')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Juan ', last_name: 'Bernal')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Mario ', last_name: 'Ramírez   ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ramon', last_name: 'Jesurum')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Jose Fernando', last_name: 'Perdomo')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Ana', last_name: 'Arizabaleta ')
Attendee.create!(category: Category.order('RANDOM()').first, email: 'yoann.lecuyer@gmail.com', event: Event.first, first_name: 'Esteban ', last_name: 'Reyes ')

user = User.create(email: "user@example.com", password: "changeme", password_confirmation: "changeme")
user.add_role :admin

